import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Fotter from "@/components/Footer/Fotter";

import Why from "@/components/Why/Why";
import Wecanhelp from "@/components/Wecanhelp/Wecanhelp";
import Whoweare from "@/components/Whoweare/Whoweare";
import Herosection from "@/components/Herosection/Herosection";
import Howwework from "@/components/Howwework/Howwework";
import Ourreferaal from "@/components/Ourreferaal/Ourreferaal";
import FindLoc from "@/components/FindLoc/FindLoc";
import Contactform from "@/components/Contactform/Contactform";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Herosection />
      <FindLoc />
      <Why />

      <Whoweare />
      <Howwework />
      <Ourreferaal />
      <Contactform />
      <Wecanhelp />
      <Fotter />
    </>
  );
}
